# Generated by Django 5.2.15 on 2026-06-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('self_review', 'Self Review'), ('company', 'Company')], max_length=20)),
                ('content', models.TextField()),
                ('interview_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='interview_stages.interviewstage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
