# Generated by Django 5.2.15 on 2026-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstage',
            name='stage_type',
            field=models.CharField(choices=[('hr', 'HR'), ('screening', 'Screening'), ('technical', 'Technical'), ('live_coding', 'Live Coding'), ('system_design', 'System Design'), ('take_home', 'Take Home'), ('client', 'Client'), ('managerial', 'Managerial'), ('final', 'Final'), ('offer', 'Offer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewstage',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('done', 'Done'), ('declined', 'Declined')], default='planned', max_length=20),
        ),
    ]
